index.html

Allow linking straight to a scenario without having to use a "scary" `?s=<base64>` url.
For example something that I could use in Discord:
https://lite.koboldai.net/?scenario=KoboldGPT

allow linking to a quick start scenario

---

index.html

For local requests via https and port 443 window.location.port is empty(''). Also with https the port can be different, not just 443.

fix support for correct protocol on https

---

index.html

**Changes:**
- 'Aesthetic UI' toggle (previously under 'Chat mode settings') is now on the right panel of the 'Format settings' tab.
**Additions:**
- 'Aesthetic UI' now affects Instruct mode as well.
- Aesthetic mode:
- Text following the `seq_start` and `seq_end` is wrapped in chat bubbles and styled appropriately.
- Text outside of chat bubbles (e.g. system messages) is slightly faded out.
- Markdown mode is supported. If enabled, these settings apply:
- Expressions (text wrapped in **s) are italicized.
- Speech (text wrapped in ""s) is italicized and colorized.
- Code blocks are stylized within black blocks for multiline code or white blocks for singleline.
- Other text inside bubbles remains white.
**Pictures:**
- Markdown disabled:
- Markdown enabled:

Added optional aesthetic mode for UI of Instruct mode.

---

index.html

Improved color pickers for Aesthetic Instruct Mode Customization UI, and added support for Safari.
- Colorpickers now pop up directly below the element whose color we're editing.
- Colorpickers now work on Safari for both macOS and iOS.

Colorpicker improvements + Safari support for macOS + iOS

---

index.html

For some reason, "title" is actually "subtitle", and "name" is the card name. Keeping newlines visible improves readability.

improve chub scenario preview rendering

---

index.html

Switching on edit mode, selecting everything, and then deleting, whenever I want to restart story generation from the beginning, or forgetting to do that and losing my just made edits to Memory (or World Info), has gotten tedious enough that I broke down and implemented an option to keep them.
* Adds a `Keep Memory and World Info` checkbox box to the new session dialog, defaulting to unchecked.
* Updates `restart_newgame` with an optional `keep_memory` argument, defaulting to false.
* Call `restart_newgame` with `keep_memory` set from the checkbox selection when the New Session dialog is confirmed.
* Maybe it should be `clear_memory` for the function parameter, and have the not in the call?
* I've set the default to not keep memory, so you get same behaviour as the current version by …

Add `Keep Memory and World Info` option to New Session

---

index.html

Fixes XTTS setting being overwritten if there are more than 100 TTS voices available on the system.
Stores your xtts_speaker setting between multiple sessions
Setting const default_xtts_base = " http://localhost:8020"; to your endpoint and changing speech_synth: 0, //0 is disabled, 1000 is xtts to 1000 will have the client auto reconnect to XTTS with your prior settings on refresh.

XTTS config fixes

---

index.html

Adds a new TTS checkbox for selecting whether or not you want the entire response narrated (as before) or only dialog. This option will be enabled by default.
Order of operations:
1) ignore anything between *asterisks*
2) if there are "quotes" in reply it will only narrate those 
3) if there aren't quotes it will narrate everything besides *emotes*

Narrate only dialog option

---

index.html

Printing in story mode still includes a lot the UI, and the main text doesn't seem to flow beyond the first page in non-aesthetic mode (at least for me).
This should fix that for all modes.
- Hides top menu when printing.
- Hides input row and chat input holder when printing
- Hides bottom info/status line when printing.
- Hides action menu (if displayed) when printing.
- Allows main text/chat history to flow across multiple pages when printing.
- I've targeted this PR at `dev` branch, I'm not sure whether that is how you want things or it should got to `main`.

Add media query styles for printing

---

index.html

Fixed line dropping of memory menu elements in Android Opera.
Before
After

Fix anote/stopseq line drop

---

index.html

Cohere has recently launched a new, very good 104B LLM called [Command R+](https://txt.cohere.com/command-r-plus-microsoft-azure/) with 128k context length which is available via their API.
It's possible to use Cohere's models via OpenRouter which is already supported, but you need to buy credits to use them.
At the time of writing this PR, it's possible to use Cohere's API for free indefinitely if you use a Trial API key for non-commercial purposes and stay within its rate-limit.
This PR adds Cohere API as a new option in the API providers dropdown menu, with the possibility to use 3 of their models (Command, Command R and Command R+). It's also possible to define a preamble, which is basically a SYSTEM prompt that is sent every request natively and can be used for jailbreaks.
API …

Adding Cohere API to the list of API providers

---

index.html

I don't know if I've fixed the CSS correctly.
I was just annoyed by this buggy hamburger menu in the mobile version.
_Before:_
_After:_

CSS: .navbar-button-bar fix

---

index.html

I tweaked the positions of some of the elements in the corpo style and tried to give more pleasing colouring to various elements. 
I will look at the other styles. I think they could be brought up at the same level of visual coherence while keeping it layout-wise the same. Some of the changes are likely to reflect in other styles, due to shared elements.
*even the user mod example was updated.

refresh: Corpo-UI light visual tweaks

---

index.html

Noticed something, by default there is no BOS being prepended? since the templates that are here suppose no BOS is prepended by default, may need to be changed.

Update for Mistral V7

---

index.html

Update AllTalk Integration
* Added Standard Generation mode as an alternative to Streaming
* Integrated RVC (voice conversion) support with voice selection
* Added RVC pitch adjustment (-24 to +24)
* RVC controls automatically disable when using Streaming mode
* Standard generation mode set as default
This now opens up Kobold to all the TTS engines that AllTalk supports, as well as the RVC/Voice2voice pipeline. So for example, you can use Piper TTS, which is very low on GPU/CPU RAM and resource, then use the RVC/Voice2voice pipeline to change the TTS output to sound like any RVC based voice you want. Full details here https://github.com/erew123/alltalk_tts/wiki/RVC-(Retrieval%E2%80%90based-Voice-Conversion) along with a link to 100,000+ voices.
Streaming generation only works with the …

AllTalk update Standard & Streaming generation

---

index.html

A variant of the ideas of World Info and Vector based Long Term Memory.  While within Lite we cannot expect vector storage to exist - at least not in its traditional form of embeddings any time soon, it is possible to implement the searching algorithms they use to extract information from the entire game text which are relevant.  These are based on similarity, and after testing a few I settled on Tf-Idf - which is explained more in the links I provided in the comments within the new code.
The general basis looks for frequency of distinctive words, the snippet length and a couple of factors like that - to try and provide a better search while still remaining performant.  While this is still a fairly rudimentary implementation / integration within Lite, it runs entirely browser side and …

feature: Addition of memory snippets

---

index.html

The main objective is to consolidate scenario source handling into a smaller area of the code, to allow for easier creation or maintenance.
- The `import_scenario` function now handles the inputBox call, the `scenariodesc` values, and resets temp_scenario to null in case of errors.
- If input fields are correctly filled in on `scenario_sources`, buttons and query arguments can be handled without requiring extra code elsewhere.
- Added an "aether" query parameter for aetherroom. I hope it wasn't omitted intentionally.
- Changed some `console.log("Error:" + error)` or similar into `console.error(error)`. This logs the stack trace of the error and marks the log message in red.
---
The normal behavior for most users shouldn't have been affected. For errors, some messages changed.
A best …

Refactors remote scenario source code for easier maintenance

---

index.html

As per the [v2 spec](https://github.com/malfoyslastname/character-card-spec-v2?tab=readme-ov-file#proposed-fields), `character_book` should be nested into the `data` object.

Fix char spec v2 embedded WI import

---

index.html

The UI currently offers a simple dice mechanic "Action (Roll)" to inject randomness into the user's query, but there is no way for users to control the output format in the style of [SillyTavern's macros](https://docs.sillytavern.app/usage/core-concepts/macros/#general-macros) such as `pick`, `random`, and `roll`.
This PR adds support for these three macros as a togglable option in the Format Menu (called "Randomizing Tags", but I'm not picky about the name). For compatibility with existing SillyTavern cards that make use of these macros, I've stuck to their syntax and [implementation](https://github.com/SillyTavern/SillyTavern/blob/release/public/scripts/macros.js), though I did take the chance to extend the dice notation slightly.
I had to think about where to replace these macros when …

Feature: Randomizing macros {{random:...}}, {{pick:...}}, {{roll:...}}

---

index.html

Noticed these while working on something for https://github.com/LostRuins/lite.koboldai.net/issues/94 (no promises on that yet!). 
Four changes in total:
1. Two `<textarea>` elements had a trailing slash in the opening tag (despite not being void elements)
2. A `<td>` in the TTS settings table wasn't closed
3. The section on classifier-free guidance had an unmatched `</em>`
I think they're all harmless:
1. Trailing slashes in opening elements are ignored (including for void elements)
2. Closing the containing `<tr>` probably closes the `<td>` as well
3. Unmatched closing tags are ignored
Still nicer to fix it up though :)

Fix unmatched tags and remove trailing slashes from opening tags

---

index.html
koboldcpp_api.html
koboldcpp_api.json

Feature: Add dry_penalty_last_n to samplers tab and docs
This is to address the limitations that rep_pen_range controlling both causes in cases when a user wishes to use both Repetition Penalty and DRY. I tried to follow the format of the existing DRY block without bloating things.
Sorry if I missed anything, but this seemed to be working as intended on my local version (as klite.embd).

feat: integrate dry_penalty_last_n setting
